import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const streamingContent = [
    {
        id: '1',
        type: 'tv',
        title: 'Planet Earth II',
        description: 'A documentary series on the wildlife of planet Earth.',
        thumbnail: 'https://image.tmdb.org/t/p/w500/i2u5b2GzeOn4wPzC5jN4zW2H741.jpg',
        url: 'https://www.netflix.com/title/80183789',
        year: '2016',
        duration: '6 min',
        rating: '9.5',
        source: 'Netflix',
        sourceUrl: 'https://www.netflix.com/title/80183789',
        previewVideo: 'https://www.youtube.com/watch?v=c8aFcHFu8QM',
        genres: ['Documentary'],
        status: 'Returning Series',
        language: 'English',
      },
      {
        id: '2',
        type: 'tv',
        title: 'Breaking Bad',
        description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
        thumbnail: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
        url: 'https://www.netflix.com/title/70143836',
        year: '2008-2013',
        duration: '49 min',
        rating: '9.5',
        source: 'Netflix',
        sourceUrl: 'https://www.netflix.com/title/70143836',
        previewVideo: 'https://www.youtube.com/watch?v=HhesaQXLuRY',
        genres: ['Crime', 'Drama', 'Thriller'],
        status: 'Ended',
        language: 'English',
      },
      {
        id: '3',
        type: 'tv',
        title: 'Chernobyl',
        description: "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
        thumbnail: 'https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUm4IIuzbJ5s.jpg',
        url: 'https://www.hbo.com/chernobyl',
        year: '2019',
        duration: '330 min',
        rating: '9.4',
        source: 'HBO',
        sourceUrl: 'https://www.hbo.com/chernobyl',
        previewVideo: 'https://www.youtube.com/watch?v=s9APLXM9Ei8',
        genres: ['Drama', 'History', 'Thriller'],
        status: 'Ended',
        language: 'English',
      },
      {
        id: '4',
        type: 'tv',
        title: 'The Wire',
        description: 'The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.',
        thumbnail: 'https://image.tmdb.org/t/p/w500/4lbFVDAcX1H91sVfgblWbC522j.jpg',
        url: 'https://www.hbo.com/the-wire',
        year: '2002-2008',
        duration: '59 min',
        rating: '9.3',
        source: 'HBO',
        sourceUrl: 'https://www.hbo.com/the-wire',
        previewVideo: 'https://www.youtube.com/watch?v=9qK-VGjMr8g',
        genres: ['Crime', 'Drama'],
        status: 'Ended',
        language: 'English',
      },
      {
        id: '5',
        type: 'tv',
        title: 'Avatar: The Last Airbender',
        description: 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
        thumbnail: 'https://image.tmdb.org/t/p/w500/c3p2hdja6ySADAm322d2E7fPwt4.jpg',
        url: 'https://www.netflix.com/title/70234489',
        year: '2005-2008',
        duration: '23 min',
        rating: '9.2',
        source: 'Netflix',
        sourceUrl: 'https://www.netflix.com/title/70234489',
        previewVideo: 'https://www.youtube.com/watch?v=d1s_104qzaQ',
        genres: ['Animation', 'Action', 'Adventure'],
        status: 'Ended',
        language: 'English',
      },
      {
        id: '6',
        type: 'movie',
        title: 'The Shawshank Redemption',
        description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        thumbnail: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        url: 'https://www.netflix.com/title/267683',
        year: '1994',
        duration: '142 min',
        rating: '9.3',
        source: 'Netflix',
        sourceUrl: 'https://www.netflix.com/title/267683',
        previewVideo: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
        genres: ['Drama', 'Crime'],
        status: 'Released',
        language: 'English',
      },
      {
        id: '7',
        type: 'movie',
        title: 'The Godfather',
        description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
        thumbnail: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        url: 'https://www.paramountplus.com/movies/the-godfather/',
        year: '1972',
        duration: '175 min',
        rating: '9.2',
        source: 'Paramount+',
        sourceUrl: 'https://www.paramountplus.com/movies/the-godfather/',
        previewVideo: 'https://www.youtube.com/watch?v=sY1S34973zA',
        genres: ['Drama', 'Crime'],
        status: 'Released',
        language: 'English',
      },
      {
        id: '8',
        type: 'movie',
        title: 'The Dark Knight',
        description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        thumbnail: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        url: 'https://www.hbo.com/movies/the-dark-knight',
        year: '2008',
        duration: '152 min',
        rating: '9.0',
        source: 'HBO',
        sourceUrl: 'https://www.hbo.com/movies/the-dark-knight',
        previewVideo: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
        genres: ['Drama', 'Action', 'Crime', 'Thriller'],
        status: 'Released',
        language: 'English',
      },
      {
        id: '9',
        type: 'movie',
        title: 'Pulp Fiction',
        description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        thumbnail: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        url: 'https://www.hbo.com/movies/pulp-fiction',
        year: '1994',
        duration: '154 min',
        rating: '8.9',
        source: 'HBO',
        sourceUrl: 'https://www.hbo.com/movies/pulp-fiction',
        previewVideo: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
        genres: ['Thriller', 'Crime'],
        status: 'Released',
        language: 'English',
      },
      {
        id: '10',
        type: 'movie',
        title: 'Forrest Gump',
        description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
        thumbnail: 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
        url: 'https://www.paramountplus.com/movies/forrest-gump/',
        year: '1994',
        duration: '142 min',
        rating: '8.8',
        source: 'Paramount+',
        sourceUrl: 'https://www.paramountplus.com/movies/forrest-gump/',
        previewVideo: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
        genres: ['Comedy', 'Drama', 'Romance'],
        status: 'Released',
        language: 'English',
      },
  ];

  for (const item of streamingContent) {
    await prisma.streamingContent.upsert({
      where: { id: item.id },
      update: item,
      create: item,
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
